// Top 1000 Irish words by frequency
window.IRISH_WORDS = [
  [1,"an","the"],[2,"bí","be"],[3,"ar","on"],[4,"agus","and"],[5,"is","is (copula)"],
  [6,"ag","at / -ing"],[7,"le","with"],[8,"na","the (plural/gen.)"],[9,"do","to / your"],[10,"go","to / that"],
  [11,"de","of / from"],[12,"sé","he / it"],[13,"sin","that"],[14,"ó","from / since"],[15,"é","him / it"],
  [16,"seo","this"],[17,"cuir","put / send"],[18,"mar","as / because"],[19,"ach","but"],[20,"déan","do / make"],
  [21,"faoi","about / under"],[22,"nó","or"],[23,"duine","person"],[24,"tabhair","give / bring"],[25,"féin","self"],
  [26,"ní","not / thing"],[27,"aon","any / one"],[28,"as","out of / from"],[29,"chun","to / towards"],[30,"eile","other / else"],
  [31,"abair","say"],[32,"mé","me / I"],[33,"tar","come"],[34,"cuid","part / share"],[35,"maith","good"],
  [36,"faigh","get / find"],[37,"sí","she"],[38,"ná","than / nor / don't"],[39,"bliain","year"],[40,"siad","they"],
  [41,"téigh","go"],[42,"nuair","when"],[43,"iad","them"],[44,"amach","out"],[45,"mo","my"],
  [46,"cé","who / which"],[47,"nach","that not / not?"],[48,"bain","extract / win / reap"],[49,"ceann","head / one"],[50,"gach","every"],
  [51,"tú","you"],[52,"rud","thing"],[53,"í","her"],[54,"caith","spend / throw / wear"],[55,"Gaeilge","Irish (language)"],
  [56,"trí","three / through"],[57,"gan","without"],[58,"féidir","possible"],[59,"lá","day"],[60,"chomh","as / so (equally)"],
  [61,"fear","man"],[62,"isteach","in / into"],[63,"fad","length / while"],[64,"áit","place"],[65,"beag","small"],
  [66,"am","time"],[67,"chuig","to / towards"],[68,"Éire","Ireland"],[69,"obair","work"],[70,"céad","first / hundred"],
  [71,"amháin","only / one"],[72,"taobh","side"],[73,"anois","now"],[74,"céile","spouse / each other"],[75,"mac","son"],
  [76,"feic","see"],[77,"níos","more (comparative)"],[78,"má","if"],[79,"teach","house"],[80,"ceart","right / correct"],
  [81,"gur","that (past/copula)"],[82,"idir","between"],[83,"scéal","story / news"],[84,"tír","country / land"],[85,"saol","life / world"],
  [86,"bith","any / existence"],[87,"roimh","before"],[88,"féad","be able"],[89,"ceist","question"],[90,"ansin","then / there"],
  [91,"deireadh","end"],[92,"bean","woman / wife"],[93,"dóigh","way / manner / burn"],[94,"dá","if / two (leniting)"],[95,"fios","knowledge"],
  [96,"uair","time / hour / once"],[97,"alt","joint / article / section"],[98,"te","hot"],[99,"pobal","community / public"],[100,"comhairle","council / advice"],
  [101,"éirigh","rise / become"],[102,"i","in"],[103,"aghaidh","face / against"],[104,"céanna","same"],[105,"arsa","said (quoting)"],
  [106,"súil","eye / hope"],[107,"scoil","school"],[108,"síos","down"],[109,"fág","leave"],[110,"nua","new"],
  [111,"glac","accept / take"],[112,"roinn","divide / share / department"],[113,"arís","again"],[114,"maidir","regarding"],[115,"teanga","language / tongue"],
  [116,"cás","case"],[117,"úsáid","use"],[118,"leith","half / particular"],[119,"iarr","ask / request"],[120,"tóg","build / raise / take"],
  [121,"óg","young"],[122,"níor","did not"],[123,"anseo","here"],[124,"thar","over / past / beyond"],[125,"tuig","understand"],
  [126,"oíche","night"],[127,"aire","attention / care / minister"],[128,"baile","home / town"],[129,"cad","what"],[130,"lucht","people / group"],
  [131,"cúrsa","course"],[132,"eolas","knowledge / information"],[133,"imigh","leave / go away"],[134,"méid","amount / size"],[135,"leor","enough"],
  [136,"lean","follow / continue"],[137,"fada","long"],[138,"caint","talk / speech"],[139,"leabhar","book"],[140,"scríobh","write"],
  [141,"acht","act (legislation)"],[142,"seachtain","week"],[143,"feidhm","function / use"],[144,"lámh","hand"],[145,"ceap","think / compose / block"],
  [146,"tarlaigh","happen"],[147,"ais","back (ar ais)"],[148,"mí","month"],[149,"léir","clear / entire"],[150,"áirigh","count / include / feel"],
  [151,"ábhar","subject / material / cause"],[152,"féach","look / try"],[153,"bealach","way / road"],[154,"ard","high / tall"],[155,"páiste","child"],
  [156,"muintir","people / family"],[157,"airgead","money"],[158,"béal","mouth"],[159,"freisin","also"],[160,"bord","table / board"],
  [161,"rialtas","government"],[162,"uile","all / every"],[163,"siúil","walk"],[164,"bunaigh","establish / found"],[165,"gabh","go / take / seize"],
  [166,"diaidh","after (i ndiaidh)"],[167,"stát","state"],[168,"ainm","name"],[169,"suas","up"],[170,"athair","father"],
  [171,"dia","God / god"],[172,"fós","yet / still"],[173,"ár","our"],[174,"ea","it (in copula)"],[175,"seirbhís","service"],
  [176,"éigin","some / certain"],[177,"clár","programme / board / plain"],[178,"talamh","land / ground"],[179,"buail","hit / strike / meet"],[180,"riamh","ever / never"],
  [181,"muid","we / us"],[182,"focal","word"],[183,"tús","beginning / start"],[184,"mise","me (emphatic)"],[185,"beirt","two people / pair"],
  [186,"fiú","worth / even"],[187,"linn","with us / pool / age"],[188,"fan","wait / stay"],[189,"dar","by (in oaths) / according to"],[190,"contae","county"],
  [191,"foireann","team / staff"],[192,"meas","respect / think / estimate"],[193,"measc","mix / among (i measc)"],[194,"leag","knock / lay down"],[195,"bóthar","road"],
  [196,"labhair","speak"],[197,"clois","hear"],[198,"cónaí","living / dwelling"],[199,"ceol","music"],[200,"bás","death"],
  [201,"cur","putting / sowing"],[202,"nár","that not (past)"],[203,"tosaigh","start / begin"],[204,"ceantar","area / district"],[205,"údarás","authority"],
  [206,"léirigh","show / demonstrate"],[207,"gá","need / necessity"],[208,"thart","around / over / past"],[209,"minic","often"],[210,"cluiche","game / match"],
  [211,"anuas","down (from above)"],[212,"iomlán","total / complete"],[213,"cóir","fair / just / ought"],[214,"conradh","contract / league"],[215,"ionad","centre / place"],
  [216,"uisce","water"],[217,"díreach","exactly / straight / just"],[218,"geall","bet / promise / pledge"],[219,"oileán","island"],[220,"cinn","of head / decide"],
  [221,"leithéid","the like / such"],[222,"cuma","shape / appearance / don't care"],[223,"cúpla","couple / a few / twins"],[224,"oideachas","education"],[225,"beir","bear / catch / give birth"],
  [226,"mol","praise / suggest / recommend"],[227,"aois","age"],[228,"cineál","kind / type / sort of"],[229,"inis","tell / island"],[230,"oiread","amount / as much"],
  [231,"líon","fill / number / net"],[232,"páirtí","party"],[233,"ball","member / limb"],[234,"lán","full"],[235,"siar","west / back"],
  [236,"cúirt","court"],[237,"cathair","city"],[238,"máthair","mother"],[239,"náisiúnta","national"],[240,"sampla","example"],
  [241,"lig","let / allow"],[242,"doras","door"],[243,"uí","grandson of (in surnames)"],[244,"oifig","office"],[245,"timpeall","around"],
  [246,"tarraing","pull / draw / attract"],[247,"bun","bottom / base / origin"],[248,"cos","foot / leg"],[249,"éagsúil","different / various"],[250,"dún","close / fort"],
  [251,"cáin","tax / criticise"],[252,"córas","system"],[253,"istigh","inside"],[254,"forbair","develop"],[255,"post","post / job / mail"],
  [256,"airteagal","article"],[257,"croí","heart"],[258,"mórán","much / many"],[259,"rith","run"],[260,"seisean","he (emphatic)"],
  [261,"seas","stand"],[262,"barr","top / tip"],[263,"dáil","Dáil / meeting / share out"],[264,"siúd","that / those (over there)"],[265,"tréimhse","period / spell"],
  [266,"imeacht","event / departure / going"],[267,"sásta","happy / satisfied"],[268,"breá","fine / lovely"],[269,"amuigh","outside"],[270,"cúis","cause / reason / court case"],
  [271,"réir","according to / order"],[272,"deis","opportunity / right (side)"],[273,"áirithe","certain / particular"],[274,"áitiúil","local"],[275,"saothar","work / labour"],
  [276,"coiste","committee"],[277,"aimsir","weather / time / tense"],[278,"maidin","morning"],[279,"toradh","result / fruit"],[280,"inniu","today"],
  [281,"suigh","sit"],[282,"breis","extra / more"],[283,"each","horse / steed"],[284,"fuil","blood"],[285,"tosach","beginning / front"],
  [286,"tuairim","opinion"],[287,"béarla","English (language)"],[288,"láthair","present / site"],[289,"ealaín","art"],[290,"comhlacht","company / body"],
  [291,"domhan","world"],[292,"coinnigh","keep / hold"],[293,"tit","fall"],[294,"dán","poem / fate"],[295,"caoi","way / means / opportunity"],
  [296,"mura","if not / unless"],[297,"meán","middle / medium / means"],[298,"tí","of a house (gen.)"],[299,"sráid","street"],[300,"gnó","business"],
  [301,"deir","says"],[302,"tamall","a while"],[303,"fíor","true"],[304,"seol","send / sail / direct"],[305,"cheana","already"],
  [306,"iarratas","application / request"],[307,"caill","lose"],[308,"múinteoir","teacher"],[309,"Gaillimh","Galway"],[310,"cara","friend"],
  [311,"seomra","room"],[312,"breathnaigh","look / watch / observe"],[313,"gearr","short / cut"],[314,"cosúil","similar / apparently"],[315,"luaigh","mention"],
  [316,"dlí","law"],[317,"iarracht","attempt / effort"],[318,"cúig","five"],[319,"nós","custom / habit"],[320,"sula","before (conjunction)"],
  [321,"áfach","however"],[322,"míle","thousand / mile"],[323,"rí","king"],[324,"slí","way / road"],[325,"úd","that / yonder"],
  [326,"saor","free / cheap / craftsman"],[327,"foilsigh","publish"],[328,"ann","there / in it"],[329,"creid","believe"],[330,"luath","early / fast"],
  [331,"deas","nice / right (side) / south"],[332,"fás","grow / growth"],[333,"iúl","guide / knowledge"],[334,"síl","think / suppose"],[335,"grúpa","group"],
  [336,"coláiste","college"],[337,"láidir","strong"],[338,"um","about / around (time)"],[339,"fáth","reason"],[340,"treo","direction / towards"],
  [341,"déag","-teen"],[342,"fadhb","problem"],[343,"cá","where"],[344,"sláinte","health"],[345,"coinne","appointment / expectation"],
  [346,"cúl","back / behind"],[347,"pléigh","discuss / deal with"],[348,"cas","turn / twist / meet"],[349,"dara","second"],[350,"in aghaidh","against / per"],
  [351,"aontaigh","agree"],[352,"sagart","priest"],[353,"mair","live / last / survive"],[354,"sórt","sort / kind"],[355,"Eorpach","European"],
  [356,"tábhachtach","important"],[357,"cead","permission"],[358,"mír","piece / item / segment"],[359,"don","to the / for the"],[360,"dó","to him / two / burn"],
  [361,"bonn","sole / coin / basis"],[362,"beo","alive / living"],[363,"íoc","pay"],[364,"dubh","black"],[365,"scéim","scheme"],
  [366,"seans","chance"],[367,"fómhar","autumn / harvest"],[368,"bocht","poor"],[369,"aithin","recognise"],[370,"cor","turn / twist / movement"],
  [371,"cogadh","war"],[372,"poiblí","public"],[373,"thiar","in the west / behind"],[374,"amhrán","song"],[375,"tuill","earn / deserve"],
  [376,"foghlaim","learn / learning"],[377,"lacha","duck"],[378,"cailín","girl"],[379,"gaoth","wind"],[380,"céim","step / degree / stage"],
  [381,"ceathair","four"],[382,"bia","food"],[383,"dream","group / crowd"],[384,"cumas","ability / power"],[385,"amhlaidh","likewise / so"],
  [386,"at","swell / swelling"],[387,"tráth","time / once / occasion"],[388,"clann","children / family"],[389,"leanbh","child / baby"],[390,"leas","benefit / welfare"],
  [391,"fonn","desire / tune / eagerness"],[392,"oscail","open"],[393,"stair","history"],[394,"críoch","end / boundary / territory"],[395,"brí","meaning / force / vigour"],
  [396,"athraigh","change"],[397,"cúram","care / responsibility"],[398,"ollscoil","university"],[399,"ceannas","authority / dominance"],[400,"seachas","rather than / compared to"],
  [401,"ól","drink"],[402,"cosain","defend / cost / protect"],[403,"cibé","whoever / whatever"],[404,"díol","sell / sale"],[405,"iontach","wonderful / very"],
  [406,"roinnt","some / a number of"],[407,"imir","play (a game)"],[408,"más","if it is"],[409,"loch","lake"],[410,"abhaile","home(wards)"],
  [411,"athrú","change (noun)"],[412,"leibhéal","level"],[413,"forbairt","development"],[414,"cumhacht","power"],[415,"cumann","association / society"],
  [416,"toisc","because / factor"],[417,"bád","boat"],[418,"grá","love"],[419,"ionann","same / equal"],[420,"soláthair","supply / provide"],
  [421,"crann","tree"],[422,"ocht","eight"],[423,"tacaíocht","support"],[424,"páirt","part / role"],[425,"farraige","sea"],
  [426,"cónaigh","dwell / live / reside"],[427,"cloch","stone"],[428,"cinnte","certain / sure"],[429,"sinn","we / us"],[430,"glan","clean / clear"],
  [431,"comórtas","competition"],[432,"solas","light"],[433,"foirm","form"],[434,"teastaigh","be needed / want"],[435,"tuaisceart","north"],
  [436,"teideal","title"],[437,"litir","letter"],[438,"gné","aspect / feature / gender"],[439,"plean","plan"],[440,"suim","interest / sum"],
  [441,"cruthaigh","create / prove"],[442,"páirc","park / field"],[443,"beatha","life / livelihood"],[444,"teaghlach","household / family"],[445,"léann","learning / scholarship"],
  [446,"bó","cow"],[447,"Mór","big / great (in names)"],[448,"aithne","acquaintance / knowing"],[449,"rogha","choice"],[450,"bris","break"],
  [451,"pointe","point"],[452,"bailigh","collect / gather"],[453,"cuairt","visit"],[454,"dath","colour"],[455,"Sasana","England"],
  [456,"olc","bad / evil"],[457,"im","butter"],[458,"file","poet"],[459,"bog","soft / move"],[460,"leath","half / spread"],
  [461,"sóisialta","social"],[462,"laghad","least / smallness"],[463,"féile","festival / generosity"],[464,"uasal","noble / Mr."],[465,"conas","how"],
  [466,"léigh","read"],[467,"deacair","difficult"],[468,"ceannaigh","buy"],[469,"lorg","seek / track / trace"],[470,"aontas","union"],
  [471,"clog","clock / bell"],[472,"té","person who / the one who"],[473,"maraigh","kill"],[474,"thuaidh","to the north / northward"],[475,"dírigh","straighten / direct / focus"],
  [476,"gníomh","action / deed"],[477,"grian","sun"],[478,"dócha","likely / probable"],[479,"socraigh","settle / arrange / decide"],[480,"úr","fresh / new"],
  [481,"deireanach","last / late"],[482,"freagra","answer"],[483,"comhphobal","community"],[484,"cuí","suitable / fitting"],[485,"arm","army"],
  [486,"buachaill","boy"],[487,"dáta","date"],[488,"Domhnach","Sunday"],[489,"dul","going"],[490,"bán","white"],
  [491,"éigean","force / necessity"],[492,"amhras","doubt / suspicion"],[493,"scaoil","release / loosen / shoot"],[494,"sibh","you (plural)"],[495,"lár","centre / middle"],
  [496,"píosa","piece"],[497,"thíos","below / down there"],[498,"trácht","traffic / mention / comment"],[499,"líne","line"],[500,"ór","gold"],
  [501,"seacht","seven"],[502,"tráthnóna","evening / afternoon"],[503,"éist","listen"],[504,"rang","class"],[505,"samhradh","summer"],
  [506,"fóill","yet / still / patience"],[507,"dúchas","heritage / native place"],[508,"turas","journey / trip"],[509,"os","above / over"],[510,"mó","bigger / more"],
  [511,"ith","eat"],[512,"tuairisc","report"],[513,"speisialta","special"],[514,"cuimhne","memory"],[515,"comhair","towards (in front of)"],
  [516,"téarma","term"],[517,"cuireadh","invitation"],[518,"luigh","lie (down)"],[519,"beith","being / birch tree"],[520,"riail","rule"],
  [521,"Meiriceá","America"],[522,"fógra","notice / advertisement"],[523,"thuas","up / above"],[524,"páipéar","paper"],[525,"beart","plan / deed / bundle"],
  [526,"tagair","refer"],[527,"cabhair","help"],[528,"sraith","series / row"],[529,"treoir","guidance / direction"],[530,"léamh","reading"],
  [531,"tine","fire"],[532,"áireamh","counting / calculation"],[533,"corp","body"],[534,"craobh","branch / championship"],[535,"oifigeach","officer / official"],
  [536,"nigh","wash"],[537,"fill","return / fold"],[538,"mian","desire / wish"],[539,"cultúr","culture"],[540,"deara","notice (ar a shúile)"],
  [541,"siopa","shop"],[542,"Éireannach","Irish (person)"],[543,"mínigh","explain"],[544,"amharc","look / view"],[545,"oibrigh","work / operate"],
  [546,"reacht","statute / act"],[547,"cuimhnigh","remember"],[548,"intinn","mind / intention"],[549,"polasaí","policy"],[550,"capall","horse"],
  [551,"scannán","film"],[552,"freagair","answer / reply"],[553,"gníomhaíocht","activity"],[554,"bua","victory / talent"],[555,"údar","author / cause"],
  [556,"leaba","bed"],[557,"comhalta","member / fellow"],[558,"tuismitheoir","parent"],[559,"deich","ten"],[560,"rún","secret / intention / resolution"],
  [561,"teilifís","television"],[562,"dearg","red"],[563,"tagairt","reference"],[564,"freastail","attend / serve"],[565,"eagla","fear"],
  [566,"baint","connection / relevance"],[567,"slán","safe / goodbye / whole"],[568,"ainneoin","despite"],[569,"garda","guard / police officer"],[570,"braith","depend / feel / sense"],
  [571,"leasaigh","amend / improve"],[572,"ceangail","tie / bind / connect"],[573,"laistigh","within"],[574,"raidió","radio"],[575,"éadach","cloth / clothes"],
  [576,"tionchar","influence"],[577,"idirnáisiúnta","international"],[578,"eagraíocht","organisation"],[579,"aird","attention / height / direction"],[580,"fáilte","welcome"],
  [581,"aer","air"],[582,"pós","marry"],[583,"beagán","a little / few"],[584,"dráma","drama"],[585,"caighdeán","standard"],
  [586,"fiche","twenty"],[587,"luach","value / price"],[588,"pictiúr","picture"],[589,"déanach","late"],[590,"airgeadas","finance"],
  [591,"domhain","deep"],[592,"sise","she (emphatic)"],[593,"feidhmigh","function / implement"],[594,"coinníoll","condition"],[595,"sliabh","mountain"],
  [596,"réitigh","solve / prepare / clear"],[597,"réidh","ready / smooth / finished"],[598,"fírinne","truth"],[599,"foinse","source"],[600,"ré","era / period / moon"],
  [601,"neart","strength / plenty"],[602,"comhar","cooperation"],[603,"tusa","you (emphatic)"],[604,"oifigiúil","official"],[605,"uachtarán","president"],
  [606,"toil","will / desire"],[607,"modh","mode / method / mood"],[608,"cum","compose / shape"],[609,"scríbhneoir","writer"],[610,"triúr","three people"],
  [611,"leigheas","cure / medicine"],[612,"scrúdú","exam / examination"],[613,"Nollaig","Christmas / December"],[614,"pleanáil","planning"],[615,"fógair","announce / proclaim"],
  [616,"cuidigh","help"],[617,"roghnaigh","choose / select"],[618,"iontas","surprise / wonder"],[619,"smaoineamh","thought / idea"],[620,"cuideachta","company"],
  [621,"stop","stop"],[622,"cuntas","account"],[623,"creideamh","belief / faith / religion"],[624,"aonar","alone / one person"],[625,"páirteach","involved / participating"],
  [626,"taispeáin","show / display"],[627,"geal","bright / white"],[628,"filíocht","poetry"],[629,"baol","danger"],[630,"tiarna","lord"],
  [631,"ciallaigh","mean / signify"],[632,"láithreach","immediately / present"],[633,"coimeád","keep / maintain"],[634,"marbh","dead"],[635,"críochnaigh","finish / complete"],
  [636,"smaoinigh","think"],[637,"teacht","coming / arrival"],[638,"deoch","drink (noun)"],[639,"parlaimint","parliament"],[640,"os cionn","above / over"],
  [641,"álainn","beautiful"],[642,"greim","grip / bite / stitch"],[643,"carr","car"],[644,"fosta","also (Ulster)"],[645,"staidéar","study"],
  [646,"suíomh","site / position"],[647,"aimsigh","find / locate"],[648,"géar","sharp / keen"],[649,"dalta","pupil / foster-child"],[650,"gar","near / favour"],
  [651,"deo","ever (go deo)"],[652,"faisnéis","information"],[653,"costas","cost"],[654,"port","tune / port / bank"],[655,"trom","heavy"],
  [656,"fianaise","evidence / witness"],[657,"droim","back / ridge"],[658,"dáiríre","serious / really"],[659,"iompair","carry / behave"],[660,"troid","fight"],
  [661,"anam","soul"],[662,"leagan","version / laying down"],[663,"teagasc","teaching / instruction"],[664,"cruinniú","meeting / gathering"],[665,"eagraigh","organise"],
  [666,"bhuel","well"],[667,"ócáid","occasion"],[668,"codail","sleep"],[669,"uimhir","number"],[670,"tuath","laity / north / countryside"],
  [671,"brath","betray / depend / intend"],[672,"dochtúir","doctor"],[673,"fiafraigh","ask / inquire"],[674,"ciall","sense / meaning"],[675,"ardaigh","raise / lift"],
  [676,"buaigh","win"],[677,"oidhreacht","heritage / inheritance"],[678,"cinntigh","ensure / make certain"],[679,"abhainn","river"],[680,"deimhin","certain / sure"],
  [681,"cothaigh","nourish / maintain / foster"],[682,"á","being (verbal particle)"],[683,"glas","green / grey / lock"],[684,"airde","height / attention"],[685,"soiléir","clear / obvious"],
  [686,"pearsanta","personal"],[687,"foras","institution / basis / growth"],[688,"aistrigh","move / translate"],[689,"spéis","interest"],[690,"dualgas","duty"],
  [691,"iníon","daughter"],[692,"dearmad","mistake / forgetting"],[693,"sín","stretch / extend"],[694,"próiseas","process"],[695,"spórt","sport / fun"],
  [696,"fostaíocht","employment"],[697,"banc","bank"],[698,"gleann","glen / valley"],[699,"litríocht","literature"],[700,"comhlíon","fulfil"],
  [701,"sean","old"],[702,"polaitíocht","politics"],[703,"réim","regime / range"],[704,"ráiteas","statement"],[705,"iarthar","west"],
  [706,"sonraigh","specify / notice"],[707,"gnáth","usual / ordinary"],[708,"beartaigh","plan / decide / intend"],[709,"guth","voice"],[710,"bronn","bestow / grant"],
  [711,"dochar","harm / damage"],[712,"slua","crowd"],[713,"cinneadh","decision"],[714,"nuachtán","newspaper"],[715,"radharc","sight / view / scene"],
  [716,"cion","share / affection / offence"],[717,"iasc","fish"],[718,"dár","of our / that was"],[719,"spreag","inspire / motivate"],[720,"margadh","market / bargain"],
  [721,"toghchán","election"],[722,"comhaontú","agreement"],[723,"brúigh","push / press"],[724,"diabhal","devil"],[725,"daonna","human"],
  [726,"leathan","wide / broad"],[727,"socrú","arrangement / settlement"],[728,"feachtas","campaign"],[729,"club","club"],[730,"deartháir","brother"],
  [731,"formhór","majority"],[732,"ordú","order"],[733,"bláth","flower / bloom"],[734,"nuacht","news"],[735,"riachtanas","requirement / necessity"],
  [736,"fuinneog","window"],[737,"teorainn","border / limit"],[738,"tuiscint","understanding"],[739,"gairid","short / near"],[740,"trasna","across"],
  [741,"taisteal","travel"],[742,"malairt","exchange / opposite"],[743,"suíochán","seat"],[744,"thall","over there"],[745,"áis","facility / convenience"],
  [746,"ainmhí","animal"],[747,"nóiméad","minute"],[748,"íseal","low"],[749,"liosta","list"],[750,"caibidil","chapter"],
  [751,"feabhas","excellence / improvement"],[752,"gáir","shout / cry / cheer"],[753,"siúl","walking"],[754,"carraig","rock"],[755,"taca","support / prop / time"],
  [756,"trá","beach / strand"],[757,"glúin","knee / generation"],[758,"stiúrthóir","director"],[759,"cumarsáid","communication"],[760,"polaitiúil","political"],
  [761,"San","Saint"],[762,"maithe","good (plural) / sake"],[763,"cnoc","hill"],[764,"Caitliceach","Catholic"],[765,"taighde","research"],
  [766,"imreoir","player"],[767,"aigne","mind"],[768,"earra","goods / item"],[769,"aonad","unit"],[770,"ceadaigh","permit / allow"],
  [771,"dúil","desire / fondness / element"],[772,"mall","slow / late"],[773,"saghas","type / sort"],[774,"duais","prize"],[775,"balla","wall"],
  [776,"taitin","please / enjoy"],[777,"tábhacht","importance"],[778,"oireachtas","assembly / Oireachtas"],[779,"méadaigh","increase"],[780,"Satharn","Saturday"],
  [781,"comhartha","sign / signal"],[782,"mála","bag"],[783,"pé","whatever / whoever"],[784,"caisleán","castle"],[785,"scil","skill"],
  [786,"saighdiúir","soldier"],[787,"múin","teach"],[788,"síocháin","peace"],[789,"nóta","note"],[790,"taithí","experience"],
  [791,"naoi","nine"],[792,"institiúid","institute"],[793,"diúltaigh","refuse / decline"],[794,"meall","lump / attract / entice"],[795,"cuspóir","aim / objective"],
  [796,"ábalta","able"],[797,"ainmnigh","name / nominate"],[798,"stáisiún","station"],[799,"vóta","vote"],[800,"ginearálta","general"],
  [801,"glór","voice / sound"],[802,"riachtanach","necessary"],[803,"imní","worry / anxiety"],[804,"gníomhaigh","act / activate"],[805,"gluais","move / glossary"],
  [806,"mothaigh","feel / notice"],[807,"ceannaire","leader"],[808,"aníos","up (from below)"],[809,"eaglais","church"],[810,"bainisteoir","manager"],
  [811,"cathaoirleach","chairperson"],[812,"eolaíocht","science"],[813,"deontas","grant"],[814,"ordaigh","order / ordain"],[815,"rialta","regular"],
  [816,"teachta","deputy / envoy"],[817,"ospidéal","hospital"],[818,"bille","bill"],[819,"cill","church / cell"],[820,"teagmháil","contact"],
  [821,"comhrá","conversation"],[822,"foirgneamh","building"],[823,"tionscal","industry"],[824,"cruinnigh","gather / assemble"],[825,"nocht","reveal / expose / bare"],
  [826,"tada","nothing"],[827,"tuarascáil","report"],[828,"rialachán","regulation"],[829,"bac","hinder / prevent / obstacle"],[830,"cloigeann","head / skull"],
  [831,"paróiste","parish"],[832,"aidhm","aim / goal"],[833,"trua","pity"],[834,"gáire","laugh / smile"],[835,"cló","print / type / shape"],
  [836,"éan","bird"],[837,"gearán","complaint"],[838,"buíochas","thanks / gratitude"],[839,"eachtra","adventure / incident"],[840,"adhmad","wood / timber"],
  [841,"poll","hole"],[842,"glaoigh","call"],[843,"scríbhinn","writing / document"],[844,"samhlaigh","imagine"],[845,"spéir","sky"],
  [846,"cruinn","round / accurate"],[847,"scór","score / twenty"],[848,"milliún","million"],[849,"éiligh","claim / demand"],[850,"ioncam","income"],
  [851,"fuar","cold"],[852,"leathanach","page"],[853,"ráta","rate"],[854,"teip","fail / failure"],[855,"Londain","London"],
  [856,"gaol","relation / relationship"],[857,"breac","trout / speckled / jot"],[858,"timpeallacht","environment"],[859,"easpa","lack / absence"],[860,"galar","disease"],
  [861,"gasúr","child / youngster"],[862,"gorm","blue"],[863,"deacracht","difficulty"],[864,"oiliúint","training"],[865,"caidreamh","relations / dealings"],
  [866,"ciúin","quiet"],[867,"can","sing"],[868,"Márta","March"],[869,"crua","hard / tough"],[870,"iarrthóir","candidate / applicant"],
  [871,"bosca","box"],[872,"peil","football"],[873,"aitheantas","recognition / identity"],[874,"theas","to the south / southern"],[875,"éineacht","together (in éineacht)"],
  [876,"traidisiún","tradition"],[877,"ullmhaigh","prepare"],[878,"réimse","range / field"],[879,"clé","left"],[880,"Luan","Monday"],
  [881,"ceangal","connection / binding"],[882,"caiteachas","expenditure"],[883,"punt","pound"],[884,"scrúdaigh","examine"],[885,"gluaiseacht","movement"],
  [886,"poblacht","republic"],[887,"beartas","policy"],[888,"cath","battle"],[889,"urlár","floor"],[890,"triail","trial / test / try"],
  [891,"seasamh","standing / stance"],[892,"fuinneamh","energy"],[893,"béim","emphasis / stress / blow"],[894,"tóir","pursuit / search"],[895,"coitianta","common"],
  [896,"éisteacht","listening / hearing"],[897,"cothrom","equal / fair / level"],[898,"sroich","reach"],[899,"cál","cabbage / reputation"],[900,"foráil","provision / provide for"],
  [901,"bainistíocht","management"],[902,"fostaí","employee"],[903,"Corcaigh","Cork"],[904,"brú","pressure / push / hostel"],[905,"taifead","record"],
  [906,"scrios","destroy"],[907,"nádúrtha","natural"],[908,"bunscoil","primary school"],[909,"eas","waterfall"],[910,"saothraigh","work / earn / cultivate"],
  [911,"iomaí","many"],[912,"scoláire","scholar / student"],[913,"teann","tight / tense / bold"],[914,"léiriú","demonstration / production"],[915,"muna","if not (variant)"],
  [916,"binn","sweet / melodious / gable / peak"],[917,"Aibreán","April"],[918,"éifeacht","effect"],[919,"beagnach","almost"],[920,"buille","blow / strike"],
  [921,"dóthain","enough"],[922,"máistir","master"],[923,"tor","bush"],[924,"níl","is not"],[925,"croch","hang / gallows"],
  [926,"amhail","like / as if"],[927,"fórsa","force"],[928,"ord","order / hammer"],[929,"déanta","done / made"],[930,"comhdháil","conference"],
  [931,"taoiseach","chief / Taoiseach"],[932,"domhanda","global / worldwide"],[933,"madra","dog"],[934,"seilbh","possession"],[935,"óige","youth"],
  [936,"laoch","hero"],[937,"iniúch","inspect / audit"],[938,"sliocht","extract / descendants / passage"],[939,"comhairleoir","councillor / advisor"],[940,"stad","stop"],
  [941,"fine","clan / fine / penalty"],[942,"long","ship"],[943,"éifeachtach","effective"],[944,"lasmuigh","outside"],[945,"gloine","glass"],
  [946,"breithiúnas","judgement"],[947,"sáraigh","surpass / violate"],[948,"on","from (dialectal)"],[949,"craiceann","skin"],[950,"cuimhin","memory / remember"],
  [951,"cosc","prevent / ban"],[952,"tionscadal","project"],[953,"iasacht","loan / borrowing"],[954,"feasta","henceforth"],[955,"iamh","enclosure"],
  [956,"cleacht","practise / custom"],[957,"go ceann","for (a period of time)"],[958,"leasú","amendment / improvement"],[959,"limistéar","area / territory"],[960,"ceithre","four (before noun)"],
  [961,"Eanáir","January"],[962,"cósta","coast"],[963,"babhta","bout / round / time"],[964,"éileamh","demand / claim"],[965,"ionsaí","attack"],
  [966,"aisteach","strange"],[967,"ionadh","surprise / wonder"],[968,"teas","heat"],[969,"méad","size / extent"],[970,"aíocht","hospitality"],
  [971,"tionscnamh","initiative / project"],[972,"cóip","copy"],[973,"bunúsach","basic / fundamental"],[974,"tae","tea"],[975,"cáilíocht","quality"],
  [976,"rás","race"],[977,"bróg","shoe"],[978,"togh","elect / choose"],[979,"breith","birth / judgement / catching"],[980,"buí","yellow / grateful"],
  [981,"cruth","shape / form"],[982,"áthas","happiness / joy"],[983,"anonn","over (to the other side)"],[984,"tuilleadh","more / additional"],[985,"téacs","text"],
  [986,"muir","sea"],[987,"suntasach","significant / notable"],[988,"tacaigh","support"],[989,"taispeántas","exhibition / display"],[990,"feirm","farm"],
  [991,"seal","spell / turn / a while"],[992,"struchtúr","structure"],[993,"iris","magazine / journal"],[994,"príosún","prison"],[995,"smacht","control / discipline"],
  [996,"eisigh","issue"],[997,"muc","pig"],[998,"halla","hall"],[999,"anocht","tonight"],[1000,"dona","bad / unfortunate"],
];
